
  create table "public"."test_deploy" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."test_deploy" enable row level security;

CREATE UNIQUE INDEX test_deploy_pkey ON public.test_deploy USING btree (id);

alter table "public"."test_deploy" add constraint "test_deploy_pkey" PRIMARY KEY using index "test_deploy_pkey";

grant delete on table "public"."test_deploy" to "anon";

grant insert on table "public"."test_deploy" to "anon";

grant references on table "public"."test_deploy" to "anon";

grant select on table "public"."test_deploy" to "anon";

grant trigger on table "public"."test_deploy" to "anon";

grant truncate on table "public"."test_deploy" to "anon";

grant update on table "public"."test_deploy" to "anon";

grant delete on table "public"."test_deploy" to "authenticated";

grant insert on table "public"."test_deploy" to "authenticated";

grant references on table "public"."test_deploy" to "authenticated";

grant select on table "public"."test_deploy" to "authenticated";

grant trigger on table "public"."test_deploy" to "authenticated";

grant truncate on table "public"."test_deploy" to "authenticated";

grant update on table "public"."test_deploy" to "authenticated";

grant delete on table "public"."test_deploy" to "service_role";

grant insert on table "public"."test_deploy" to "service_role";

grant references on table "public"."test_deploy" to "service_role";

grant select on table "public"."test_deploy" to "service_role";

grant trigger on table "public"."test_deploy" to "service_role";

grant truncate on table "public"."test_deploy" to "service_role";

grant update on table "public"."test_deploy" to "service_role";


